# Generated by Django 5.2 on 2025-05-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_autor_editorial_alter_cataleg_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplar',
            name='codi',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
