# Generated by Django 5.2 on 2025-05-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_exemplar_codi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplar',
            name='codi',
            field=models.CharField(default='EX-DEFAULT', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
