# Generated by Django 5.2 on 2025-05-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_alter_exemplar_codi'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
