# Generated by Django 5.2 on 2025-05-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0013_usuari_token_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuari',
            name='token_expires',
        ),
        migrations.AlterField(
            model_name='usuari',
            name='auth_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
