# Generated by Django 5.2 on 2025-05-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0014_remove_usuari_token_expires_alter_usuari_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='auth_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
